all: makeFileSystem fileSystemOper

makeFileSystem: makeFileSystem.cpp
	g++ makeFileSystem.cpp -o makeFileSystem 

fileSystemOper: fileSystemOper.cpp
	g++ fileSystemOper.cpp -o fileSystemOper 

clean:
	rm fileSystemOper makeFileSystem
	